import { useState } from 'react';
import { ArrowRight, Search, X, Braces, Network, RefreshCw } from 'lucide-react';
import type { SearchMode } from '../domain/types';
import { graphLocation } from '../services/navigation';
import { useStore, useWorkbench } from './context';
import { Busy, EmptyState, IconButton } from './primitives';
import { VirtualList } from './VirtualList';
export function SearchPanel() {
  const workbench = useWorkbench();
  const state = useStore(workbench.search);
  const repository = useStore(workbench.repository);
  const [query, setQuery] = useState(state.query);
  const [mode, setMode] = useState<SearchMode>(state.mode);
  return <section className="side-panel"><div className="panel-heading"><span>SEARCH</span><Braces size={15} /></div><form className="search-form" onSubmit={event => { event.preventDefault(); void workbench.perform('Searching index', () => workbench.runSearch(query, mode)); }}><div className="input-with-icon"><Search size={14} /><input aria-label="Search repository" placeholder="Search repository…" value={query} onChange={event => setQuery(event.target.value)} autoFocus /></div><div className="row"><select aria-label="Search mode" value={mode} onChange={event => setMode(event.target.value as SearchMode)}><option value="text">Text</option><option value="regex">Regular expression</option><option value="symbol">Symbols</option><option value="filename">File names</option><option value="semantic">Semantic</option></select><button disabled={!repository.current || !query.trim() || state.loading}>Search</button>{state.loading && <IconButton label="Cancel search" onClick={() => { void workbench.perform('Cancelling search', () => workbench.cancelSearch()); }}><X size={14} /></IconButton>}</div></form>{state.loading && <div className="panel-padding"><Busy label="Searching persisted index" /></div>}{state.hits.length > 0 ? <><div className="result-caption">{state.mode === 'semantic' ? `Up to 100 ranked results · ${state.hits.length} shown` : `${state.hits.length}${state.more ? '+' : ''} results · ${state.mode}`}</div><VirtualList items={state.hits} rowHeight={67} label="Search results" itemKey={hit => `${hit.path}:${hit.line}:${hit.column}:${hit.content}`} render={hit => <button className="search-result" onClick={() => { void workbench.perform('Opening result', () => workbench.openFile(hit.path, hit.line)); }}><span className="result-path">{hit.path}<span>{hit.line}:{hit.column}</span></span><code>{hit.content}</code>{hit.symbol && <span className="result-symbol">{hit.symbol}</span>}</button>} />{state.more && <button className="load-more" disabled={state.loading} onClick={() => { void workbench.perform('Loading results', () => workbench.runSearch(state.query, state.mode, true)); }}>Load next 100 results</button>}</> : !state.loading && <EmptyState icon={<Search size={26} />} title={state.query ? 'No matches' : 'Find your next starting point'}>{state.query ? 'Try another query or rebuild the repository index.' : 'Search indexed content, definitions, and file names. Index the repository before your first search.'}</EmptyState>}</section>;
}
export function GraphPanel() {
  const workbench = useWorkbench();
  const state = useStore(workbench.search);
  const editor = useStore(workbench.editor);
  const [path, setPath] = useState(state.graphPath || editor.active || '');
  const [direction, setDirection] = useState(state.direction);
  return <section className="side-panel"><div className="panel-heading"><span>CODE RELATIONSHIPS</span><Network size={15} /></div><form className="search-form" onSubmit={event => { event.preventDefault(); void workbench.perform('Querying graph', () => workbench.loadGraph(path, direction)); }}><label className="field">File or symbol<input value={path} onChange={event => setPath(event.target.value)} placeholder="src/main.ts or symbol name" /></label><select aria-label="Relationship type" value={direction} onChange={event => setDirection(event.target.value)}><option value="dependencies">Dependencies</option><option value="dependents">Dependents</option><option value="references">References</option><option value="callers">Callers</option><option value="affected">Affected files</option></select><div className="row"><button type="button" disabled={!editor.active} onClick={() => setPath(editor.active ?? '')}>Use editor file</button><button disabled={!path.trim()} className="primary">Inspect</button></div></form>{state.graph.length ? <VirtualList items={state.graph} rowHeight={84} label="Code relationships" itemKey={edge => `${edge.source}:${edge.target}:${edge.kind}`} render={edge => <div className="graph-edge"><span className="pill">{edge.kind}</span><span title={`${edge.source} → ${edge.target}`}>{edge.source} → {edge.target}</span><button disabled={graphLocation(edge, state.direction).external} title={graphLocation(edge, state.direction).external ? 'External module; no local file to open' : graphLocation(edge, state.direction).label} onClick={() => { void workbench.perform('Opening source location', () => workbench.openGraphLocation(edge)); }}><ArrowRight size={13} />{graphLocation(edge, state.direction).label}</button></div>} /> : <EmptyState icon={<Network size={28} />} title="Follow the code">Inspect relationships from the repository index. Unresolved external imports are shown without file navigation.</EmptyState>}</section>;
}
export function HealthPanel() {
  const workbench = useWorkbench();
  const state = useStore(workbench.repository);
  const ui = useStore(workbench.ui);
  return <section className="side-panel"><div className="panel-heading"><span>REPOSITORY HEALTH</span><IconButton label="Refresh health" disabled={!state.current} onClick={() => { void workbench.perform('Refreshing health', () => workbench.refreshHealth()); }}><RefreshCw size={14} /></IconButton></div><div className="panel-padding scroll"><div className="section-label">INDEX</div><div className="row"><button disabled={!state.current || state.indexing} onClick={() => { void workbench.perform('Indexing repository', () => workbench.indexRepository()); }}>Build index</button>{state.indexing && <button onClick={() => { void workbench.perform('Cancelling index', () => workbench.cancelIndex()); }}>Cancel</button>}</div>{state.indexing && <Busy label="Indexing repository" />}{state.index && <dl className="metrics"><div><dt>Files</dt><dd>{state.index.files.toLocaleString()}</dd></div><div><dt>Symbols</dt><dd>{state.index.symbols.toLocaleString()}</dd></div><div><dt>Dependencies</dt><dd>{state.index.dependencies.toLocaleString()}</dd></div><div><dt>Duration</dt><dd>{state.index.durationMs.toLocaleString()} ms</dd></div></dl>}<div className="section-label">PERSISTED METRICS</div>{state.health ? <pre className="json-view">{JSON.stringify(state.health, null, 2)}</pre> : <p className="muted">Open a repository to inspect its index.</p>}<div className="section-label">RECENT DIAGNOSTICS</div>{ui.notices.length ? ui.notices.map(notice => <div className="diagnostic" key={notice.id}><code>{notice.error.code}</code><span>{notice.error.message}</span></div>) : <p className="muted">No errors reported in this application session.</p>}</div></section>;
}
