CREATE TABLE agent_imports(id TEXT PRIMARY KEY,data TEXT NOT NULL);
CREATE TABLE agent_sessions(id TEXT PRIMARY KEY,repository_id TEXT NOT NULL,created_at INTEGER NOT NULL,data TEXT NOT NULL);
CREATE TABLE command_runs(id TEXT PRIMARY KEY,repository_id TEXT NOT NULL,program TEXT NOT NULL,args_json TEXT NOT NULL,cwd TEXT NOT NULL,env_names_json TEXT NOT NULL,is_test INTEGER NOT NULL,status TEXT NOT NULL,started_at INTEGER NOT NULL,duration_ms INTEGER NOT NULL DEFAULT 0,exit_code INTEGER,output_json TEXT NOT NULL DEFAULT '[]',truncated INTEGER NOT NULL DEFAULT 0);
CREATE TABLE diagnostics(id INTEGER PRIMARY KEY,at INTEGER NOT NULL,category TEXT NOT NULL,duration_ms INTEGER NOT NULL,message TEXT NOT NULL);
CREATE TABLE embeddings(repository_id TEXT NOT NULL,path TEXT NOT NULL,provider TEXT NOT NULL,hash TEXT NOT NULL,vector TEXT NOT NULL,content TEXT NOT NULL,PRIMARY KEY(repository_id,path,provider));
CREATE TABLE index_edges(repository_id TEXT NOT NULL,source TEXT NOT NULL,target TEXT NOT NULL,kind TEXT NOT NULL,PRIMARY KEY(repository_id,source,target,kind));
CREATE TABLE index_files(repository_id TEXT NOT NULL,path TEXT NOT NULL,content TEXT NOT NULL,hash TEXT NOT NULL,language TEXT NOT NULL,size INTEGER NOT NULL,parse_errors INTEGER NOT NULL,generation TEXT NOT NULL,PRIMARY KEY(repository_id,path));
CREATE TABLE index_references(repository_id TEXT NOT NULL,path TEXT NOT NULL,name TEXT NOT NULL,kind TEXT NOT NULL,line INTEGER NOT NULL,column_no INTEGER NOT NULL);
CREATE TABLE index_runs(id TEXT PRIMARY KEY,repository_id TEXT NOT NULL,status TEXT NOT NULL,started_at INTEGER NOT NULL,duration_ms INTEGER NOT NULL DEFAULT 0,files INTEGER NOT NULL DEFAULT 0,error TEXT);
CREATE TABLE index_symbols(repository_id TEXT NOT NULL,path TEXT NOT NULL,name TEXT NOT NULL,kind TEXT NOT NULL,line INTEGER NOT NULL,column_no INTEGER NOT NULL,end_line INTEGER NOT NULL);
CREATE VIRTUAL TABLE index_text USING fts5(content,content='index_files',content_rowid='rowid',tokenize='trigram case_sensitive 1');
CREATE TABLE patch_journal(patch_id TEXT PRIMARY KEY REFERENCES patch_sets(id),repository_id TEXT NOT NULL REFERENCES repositories(id),prior_status TEXT NOT NULL,operation TEXT NOT NULL,items TEXT NOT NULL,started_at INTEGER NOT NULL);
CREATE TABLE patch_sets(id TEXT PRIMARY KEY,repository_id TEXT NOT NULL REFERENCES repositories(id),status TEXT NOT NULL,source TEXT NOT NULL,created_at INTEGER NOT NULL,changes TEXT NOT NULL);
CREATE TABLE repositories(id TEXT PRIMARY KEY,root TEXT NOT NULL UNIQUE,name TEXT NOT NULL,opened_at INTEGER NOT NULL);
CREATE TABLE repository_memory(repository_id TEXT NOT NULL,fact TEXT NOT NULL,created_at INTEGER NOT NULL,PRIMARY KEY(repository_id,fact));
CREATE TABLE settings(key TEXT PRIMARY KEY,value TEXT NOT NULL);
CREATE TABLE tool_calls(id TEXT PRIMARY KEY,session_id TEXT NOT NULL,timestamp INTEGER NOT NULL,arguments TEXT NOT NULL,result TEXT NOT NULL,duration_ms INTEGER NOT NULL,status TEXT NOT NULL);
CREATE INDEX command_repository ON command_runs(repository_id,started_at);
CREATE INDEX index_edge_target ON index_edges(repository_id,target);
CREATE INDEX index_reference_name ON index_references(repository_id,name);
CREATE INDEX index_reference_path ON index_references(repository_id,path);
CREATE INDEX index_run_repository ON index_runs(repository_id,started_at);
CREATE INDEX index_symbol_name ON index_symbols(repository_id,name COLLATE NOCASE);
CREATE INDEX index_symbol_path ON index_symbols(repository_id,path);
CREATE INDEX journal_repository ON patch_journal(repository_id);
CREATE INDEX patch_repository ON patch_sets(repository_id,created_at DESC);
